default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  database: project_test

production:
  url: <%= ENV['DATABASE_URL'] %>
